name: build docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: login docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: ls
      run: ls -lh && ls -lh ../
      shell: bash
    - name: Build the Docker image
      run: docker build --no-cache -t wajika/kafka-docker:latest ../kafka-docker/
    - name: push hub
      run: docker push wajika/kafka-docker:latest
