name: build docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: login docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build -t --no-cache wajika/kafka-docker:latest .
    - name: push hub
      run: docker push wajika/kafka-docker:latest
